### ISSUE TITLE
Hello brother

### ISSUE THREAD

**Issue by NeaGogu** [janelu44/rune_legend#17]
Nu mai merge varule reparal te rog io ca vreau si io sa ma joc liga legendel0r.

**Comment by janelu44** [comment]
gata fraticu zi cei facem punem softu ala nou

**Comment by NeaGogu** [comment]
![IMG-20220612-WA0003.jpeg](https://user-images.githubusercontent.com/70640237/173538532-1bd7c4c8-6c91-4a1a-9b45-865a389f797a.jpeg)

**Comment by NeaGogu** [comment]
esti tarfa daca mai stergi

**Comment by janelu44** [comment]
te scot de la mostenitori

**Comment by LeTeutz** [comment]
![image](https://user-images.githubusercontent.com/29125437/173662360-f5dff2d3-cbd3-4d5a-802e-514fb5aee1a9.png)

**Comment by NeaGogu** [comment]
https://user-images.githubusercontent.com/70640237/173666007-09c36b25-a8d4-4e16-b7c4-f106141a5678.mov

**Comment by NeaGogu** [comment]
Ba sefule nu stiu ce sa i fac cand rulez programu cu sarpele asta piton imi apare asta. ce sai fac?? 

> dau funda

![450](https://user-images.githubusercontent.com/70640237/173666272-efb83460-1388-4356-b7d1-a3de88dc6558.png)
