### ISSUE TITLE
Add cs go functionality

### ISSUE THREAD

**Issue by acturcu** [janelu44/rune_legend#20]
![image](https://user-images.githubusercontent.com/92313471/173916832-abc71fa3-32c5-423a-927c-f8dee540cc53.png)

**Comment by acturcu** [comment]
![image](https://user-images.githubusercontent.com/92313471/173916898-5967bd80-aa6f-408a-bd29-eb5417e14c3c.png)

**Comment by janelu44** [comment]
no sry
